CREATE OR REPLACE synonym NFDIC_DEPT FOR KLB_OAVNEXT.NFDIC_DEPT;
CREATE OR REPLACE synonym NFDIC_DEPT_EMP FOR KLB_OAVNEXT.NFDIC_DEPT_EMP;
CREATE OR REPLACE synonym NFDIC_EMPLOYEE FOR KLB_OAVNEXT.NFDIC_EMPLOYEE;
CREATE OR REPLACE synonym NFSYS_ORGANIZATION FOR KLB_OAVNEXT.NFSYS_ORGANIZATION;
CREATE OR REPLACE synonym NFSYS_PARAMETERS FOR KLB_OAVNEXT.NFSYS_PARAMETERS;
CREATE OR REPLACE synonym NFSYS_CATEGORY FOR KLB_OAVNEXT.NFSYS_CATEGORY;
CREATE OR REPLACE synonym NFSYS_CATEGORY_S FOR KLB_OAVNEXT.NFSYS_CATEGORY_S;