#测试环境配置
server:
  port: 8061
  servlet:
    # 应用的访问路径
    context-path: /
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:oracle:thin:@192.168.9.242:1521:orcl
    username: KLB_appointment
    password: klb2017!
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: admin-pool
  redis:
    database: 4
    host: 192.168.9.242
    port: 6379
    password: klb2017!
    timeout: 10000
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
logging:
  level:
    com.nbnfsoft.admin.repository.*: debug
  pattern:
    console: '%p%m%n'
uploadFile:
  resourceHandler: /upload/**   #请求 url 中的资源映射
  location: D:/upload/ #自定义上传文件本地保存路径
